apiVersion: v1
kind: Service
metadata:
  name: {{ include "timetable.fullname" . }}
  labels:
    {{- include "timetable.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
